### ISSUE TITLE
카테고리 추가

### ISSUE THREAD

**Issue by soohyuneeee** [Mobydick-Team/kkm_java_server_v2#29]
### ✍️ DESCRIPTION

게시글 카테고리에 `졸업사진`을 추가합니다.

### 🔨 TO DO

- [x] 게시글 카테고리에 졸업사진 추가하기
- [x] 게시글 카테고리에 전체(ALL) 추가하기

### ETC
~~꼬꼬막이 좀 더 세상에 빨리 나왔더라면 난 싼 가격에 졸업사진 옷을 대여했을텐데~~

**Comment by kimhyerin0909** [comment]
> 내년에 졸사 찍는 친구들이 꼬꼬막을 사용하길 바라며....................
